### PR TITLE
add color param to the drop shadow widget

### PR DESCRIPTION
**Pull request by jawwad-hassan89**
Added a color param to the drop shadow widget for overriding shadow color.

### CODE REVIEW

**Comment by rei-codes** [comment]
I don't understand, How is it different between with regular shadow?

**Comment by jawwad-hassan89** [comment]
This allows to set any color to the shadow, whereas the default implementation only takes the color of the widget itself. For example, if the container color is blue, the default implementation will always set the shadow color to blue with an opacity, with the color param, the shadow can be any color regardless of the widget color.

**Comment by rei-codes** [comment]
Thank you, I was talking about the [BoxShadow](https://api.flutter.dev/flutter/painting/BoxShadow-class.html). But I guess it's not working on png/svg images as I expected.

**Comment by rei-codes** [comment]
I changed the blend mode to srcIn to show the exact color that user give.
Thank you for the PR. I'm merging it!

**Pull request merged**
